version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:11
    ports:
      - 5433:5432
    volumes:
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_HOST_AUTH_METHOD: trust









